version: '3'

services:
  opencv:
    container_name: opencv
    build:
      context: Dockerfile.cpu
    network_mode: 'host'
    privileged: true
    volumes:
      - ./code:/code
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/video0:/dev/video0
    environment:
      - DISPLAY=$DISPLAY
    ports:
      - 8888:8888
