services:
  opencv:
    image: nicolasqueiroga/opencv-gpu:latest
    container_name: opencv-gpu
    privileged: true
    shm_size: '8gb'
    volumes:
      - ./code:/home/code
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/video0:/dev/video0
    environment:
      - DISPLAY=$DISPLAY
    networks:
      - sudoku-solver-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

networks:
  sudoku-solver-network:


volumes:
  sudoku-solver-volume:
