services:
  opencv:
    container_name: opencv-gpu
    image: nicolasqueiroga/opencv-gpu:latest
    shm_size: '8gb'
    network_mode: 'host'
    privileged: true
    volumes:
      - ./code:/code
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/video0:/dev/video0
    environment:
      - DISPLAY=$DISPLAY
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
