services:
  opencv:
    image: nicolasqueiroga/opencv-cpu:latest
    container_name: opencv-cpu
    privileged: true
    volumes:
      - ./code:/home/code
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/video0:/dev/video0
    environment:
      - DISPLAY=$DISPLAY
    ports:
      - 8888:8888
